;my.defineComponent || (my.defineComponent = Component);(my["webpackJsonp"]=my["webpackJsonp"]||[]).push([["app/banana/components/list"],{"1f28":function(t,a,n){"use strict";var e=n("d86b"),i=n.n(e);i.a},7433:function(t,a,n){"use strict";n.r(a);var e=n("97d5"),i=n.n(e);for(var u in e)"default"!==u&&function(t){n.d(a,t,(function(){return e[t]}))}(u);a["default"]=i.a},"97d5":function(t,a,n){"use strict";(function(t){Object.defineProperty(a,"__esModule",{value:!0}),a.default=void 0;var e=i(n("8565"));function i(t){return t&&t.__esModule?t:{default:t}}var u={props:{dataList:{default:function(){return[]}},info:{default:function(){return{}}},title:{default:""},isMin:{default:!1}},data:function(){return{vodid:"",videoUrl:""}},methods:{headerClick:function(){this.info.spid?(this.$store.commit("detail",this.info),t.navigateTo({url:"/app/banana/views/detail"})):t.navigateTo({url:"/app/banana/views/class"})},itemClick:function(a){var n=this;a.vodid!=this.vodid&&(t.showLoading(),t.request({url:e.default.origin+a.play_url,data:e.default.query(),success:function(e){t.hideLoading(),console.log("success",e),e.data.data.httpurl?(n.videoUrl=e.data.data.httpurl,n.vodid=a.vodid):e.data.data.httpurl_preview?(n.videoUrl=e.data.data.httpurl_preview,n.vodid=a.vodid):t.showToast({title:e.data.errmsg,icon:"none"}),document&&(document.title=a.title)},fail:function(){t.hideLoading(),t.showToast({title:"fail"})}}))}}};a.default=u}).call(this,n("c11b")["default"])},"9b5e":function(t,a,n){"use strict";var e;n.d(a,"b",(function(){return i})),n.d(a,"c",(function(){return u})),n.d(a,"a",(function(){return e}));var i=function(){var t=this,a=t.$createElement;t._self._c},u=[]},d86b:function(t,a,n){},e929:function(t,a,n){"use strict";n.r(a);var e=n("9b5e"),i=n("7433");for(var u in i)"default"!==u&&function(t){n.d(a,t,(function(){return i[t]}))}(u);n("1f28");var d,o=n("f0c5"),r=Object(o["a"])(i["default"],e["b"],e["c"],!1,null,"69de20b2",null,!1,e["a"],d);a["default"]=r.exports}}]);
;(my["webpackJsonp"] = my["webpackJsonp"] || []).push([
    'app/banana/components/list-create-component',
    {
        'app/banana/components/list-create-component':(function(module, exports, __webpack_require__){
            __webpack_require__('c11b')['createComponent'](__webpack_require__("e929"))
        })
    },
    [['app/banana/components/list-create-component']]
]);
